apiVersion: v1
kind: Secret
metadata:
  name: empldb-secret
type: Opaque
data:
  DB_User: bmFncA==
  DB_Pass: QXNtdCM1NDIx
  DB_RootPass: TWdtdCM0NTg3
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: empldb-config
data:
  DB_Host: "empldb-svc"
  DB_Port: "3306"
  DB_Name: "EmployeeDb"
  DB_Pool: "25"
  Environment: Production