apiVersion: apps/v1
kind: Deployment
metadata:
  name: emplapi-depl
  labels:
    app: employeeapi
spec:
  replicas: 4
  selector:
    matchLabels:
      app: employeeapi
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: employeeapi
    spec:
      containers:
        - name: employeeapi
          image: atharimam/employeeapi.api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          env:
            - name: POD_Name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: Environment
              valueFrom:
                configMapKeyRef:
                  name: empldb-config
                  key: Environment
            - name: DB_Host
              valueFrom:
                configMapKeyRef:
                  name: empldb-config
                  key: DB_Host
            - name: DB_Port
              valueFrom:
                configMapKeyRef:
                  name: empldb-config
                  key: DB_Port
            - name: DB_Name
              valueFrom:
                configMapKeyRef:
                  name: empldb-config
                  key: DB_Name
            - name: DB_Pool
              valueFrom:
                configMapKeyRef:
                  name: empldb-config
                  key: DB_Pool
            - name: DB_User
              valueFrom:
                secretKeyRef:
                  name: empldb-secret
                  key: DB_User
            - name: DB_Pass
              valueFrom:
                secretKeyRef:
                  name: empldb-secret
                  key: DB_Pass

---

apiVersion: v1
kind: Service
metadata:
  name: emplapi-svc
spec:
  selector:
    app: employeeapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
