apiVersion: v1
kind: PersistentVolume
metadata:
  name: empldb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /db/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: empldb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi